import {motion, useScroll, useSpring, useTransform} from "framer-motion"

const ScrollAnimations = () => {
    const {scrollYProgress} = useScroll();

    const springScaleX = useSpring(scrollYProgress)

    const background = useTransform(scrollYProgress,
        [0, 0.25, 1], 
        ["rgb(86, 1, 245)", "rgb(1, 100, 45)", "rgb(1, 245, 13)"]
        )
    return (
        <div>
            <motion.div
                style={{
                    // scaleX:scrollYProgress,
                    scaleX:springScaleX,
                    background,
                    // background: "blue",
                    position: "sticky",
                    transformOrigin:"left",
                    top: 0,
                    width: "100%",
                    height: 20,

                }}
            ></motion.div>

            <div style={{
                fontSize: "1.2rem"
            }}>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Modi dolore molestias sunt eos nulla numquam molestiae ut nam, tempora reprehenderit minima quas fuga delectus vel consequatur. Adipisci eaque atque quibusdam tenetur, pariatur architecto amet ratione doloremque voluptatem hic! Quam error ea et nobis iusto possimus vitae aut nihil, doloribus minima!
                </p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto veniam accusantium incidunt? Rerum quasi earum modi? Id, quo saepe. Sed minima facere enim, sunt vel numquam ipsum dolorum magnam porro ab perspiciatis temporibus cupiditate et quasi aliquam rerum quidem inventore provident distinctio cum! Similique, atque? Ex labore ullam repudiandae, quaerat provident quia totam mollitia odio, ipsum at, rerum praesentium? Eos, ea corporis. Tempore consequatur rem fugiat mollitia odio sed perferendis itaque ea. Deserunt error libero optio quo! Adipisci, placeat magni!</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit, velit accusamus repudiandae eum praesentium asperiores beatae, quaerat exercitationem facere, cum molestias nam? Nobis nemo doloremque dolores ea repudiandae fugit provident.</p>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium exercitationem minus animi voluptate. Voluptates ad ipsa, magni dolorem quibusdam unde saepe sint ratione, corrupti dolor id nulla, quae quidem similique assumenda iste voluptas tempora nam velit. Neque repudiandae voluptatem cum tenetur amet impedit ratione eos similique laudantium perferendis! Facilis, voluptates est pariatur, debitis veniam iste odio neque quod assumenda nulla nihil. Libero fuga id nulla distinctio incidunt similique ipsam consectetur. Facilis voluptates aliquid consectetur quibusdam sit deleniti nesciunt maiores corporis esse aperiam praesentium, omnis totam hic eligendi voluptatum assumenda voluptatibus!</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor temporibus esse cupiditate ipsum praesentium voluptatibus, unde sequi beatae ullam modi soluta odio quo possimus molestiae facilis expedita illo explicabo quidem quasi quaerat dolorem reiciendis. Quas et consequuntur impedit ipsum repudiandae voluptates modi, architecto omnis. Ducimus delectus ex nesciunt optio alias laudantium excepturi, tempora rem nulla cumque obcaecati aut asperiores ratione earum ullam nihil dolor quisquam fugiat quia magnam quidem laboriosam? Corrupti autem libero ea voluptatum mollitia, quaerat numquam facilis illum quis rerum cupiditate? Atque vitae, assumenda neque labore eligendi eaque sapiente. Odio iure id voluptatem sint voluptatum! Eaque, vero deserunt! Soluta, atque cupiditate fuga nam in sed facilis natus nihil doloremque consectetur impedit deserunt molestiae error, debitis dolor laboriosam? Sed?</p>

                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium modi quibusdam ipsum veritatis molestias tempore itaque possimus totam minus inventore quis saepe voluptatum quae aliquam, ipsa, nihil in consectetur distinctio maiores! Repellat odio pariatur, eveniet blanditiis provident ullam inventore illo dolore, nesciunt rem minima error! Et at tenetur possimus dignissimos recusandae temporibus tempore eius mollitia incidunt repellendus exercitationem hic minus ratione atque perspiciatis earum molestiae, laudantium voluptate optio nulla deserunt iusto. Hic aspernatur nam, vero dolorem dolores velit et commodi, minima necessitatibus vitae, cum beatae assumenda ea amet fugit officia est. Dolores minima aliquid praesentium accusamus eum laudantium tenetur voluptatibus at magni. Ea tempora obcaecati incidunt, ratione eveniet quia veniam a commodi maxime suscipit illo libero explicabo sint iusto officiis. Dolores, minus deserunt eos nostrum nisi consectetur. Impedit doloribus excepturi minus, facere adipisci velit laboriosam nobis sequi saepe incidunt. In, reiciendis! Reprehenderit perferendis maxime placeat repudiandae sit assumenda iure minima tempore sint illo iusto, blanditiis iste? Nobis, rem iusto. Dignissimos quidem perferendis expedita at, excepturi obcaecati non iusto soluta, tempora, et ipsam nihil? Minima officia amet esse, animi error maiores voluptate omnis autem repellendus blanditiis consectetur quas fugiat ex possimus soluta? Recusandae nisi reiciendis odit sed laboriosam quia hic animi!</p>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto veniam accusantium incidunt? Rerum quasi earum modi? Id, quo saepe. Sed minima facere enim, sunt vel numquam ipsum dolorum magnam porro ab perspiciatis temporibus cupiditate et quasi aliquam rerum quidem inventore provident distinctio cum! Similique, atque? Ex labore ullam repudiandae, quaerat provident quia totam mollitia odio, ipsum at, rerum praesentium? Eos, ea corporis. Tempore consequatur rem fugiat mollitia odio sed perferendis itaque ea. Deserunt error libero optio quo! Adipisci, placeat magni!</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit, velit accusamus repudiandae eum praesentium asperiores beatae, quaerat exercitationem facere, cum molestias nam? Nobis nemo doloremque dolores ea repudiandae fugit provident.</p>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium exercitationem minus animi voluptate. Voluptates ad ipsa, magni dolorem quibusdam unde saepe sint ratione, corrupti dolor id nulla, quae quidem similique assumenda iste voluptas tempora nam velit. Neque repudiandae voluptatem cum tenetur amet impedit ratione eos similique laudantium perferendis! Facilis, voluptates est pariatur, debitis veniam iste odio neque quod assumenda nulla nihil. Libero fuga id nulla distinctio incidunt similique ipsam consectetur. Facilis voluptates aliquid consectetur quibusdam sit deleniti nesciunt maiores corporis esse aperiam praesentium, omnis totam hic eligendi voluptatum assumenda voluptatibus!</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor temporibus esse cupiditate ipsum praesentium voluptatibus, unde sequi beatae ullam modi soluta odio quo possimus molestiae facilis expedita illo explicabo quidem quasi quaerat dolorem reiciendis. Quas et consequuntur impedit ipsum repudiandae voluptates modi, architecto omnis. Ducimus delectus ex nesciunt optio alias laudantium excepturi, tempora rem nulla cumque obcaecati aut asperiores ratione earum ullam nihil dolor quisquam fugiat quia magnam quidem laboriosam? Corrupti autem libero ea voluptatum mollitia, quaerat numquam facilis illum quis rerum cupiditate? Atque vitae, assumenda neque labore eligendi eaque sapiente. Odio iure id voluptatem sint voluptatum! Eaque, vero deserunt! Soluta, atque cupiditate fuga nam in sed facilis natus nihil doloremque consectetur impedit deserunt molestiae error, debitis dolor laboriosam? Sed?</p>

                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium modi quibusdam ipsum veritatis molestias tempore itaque possimus totam minus inventore quis saepe voluptatum quae aliquam, ipsa, nihil in consectetur distinctio maiores! Repellat odio pariatur, eveniet blanditiis provident ullam inventore illo dolore, nesciunt rem minima error! Et at tenetur possimus dignissimos recusandae temporibus tempore eius mollitia incidunt repellendus exercitationem hic minus ratione atque perspiciatis earum molestiae, laudantium voluptate optio nulla deserunt iusto. Hic aspernatur nam, vero dolorem dolores velit et commodi, minima necessitatibus vitae, cum beatae assumenda ea amet fugit officia est. Dolores minima aliquid praesentium accusamus eum laudantium tenetur voluptatibus at magni. Ea tempora obcaecati incidunt, ratione eveniet quia veniam a commodi maxime suscipit illo libero explicabo sint iusto officiis. Dolores, minus deserunt eos nostrum nisi consectetur. Impedit doloribus excepturi minus, facere adipisci velit laboriosam nobis sequi saepe incidunt. In, reiciendis! Reprehenderit perferendis maxime placeat repudiandae sit assumenda iure minima tempore sint illo iusto, blanditiis iste? Nobis, rem iusto. Dignissimos quidem perferendis expedita at, excepturi obcaecati non iusto soluta, tempora, et ipsam nihil? Minima officia amet esse, animi error maiores voluptate omnis autem repellendus blanditiis consectetur quas fugiat ex possimus soluta? Recusandae nisi reiciendis odit sed laboriosam quia hic animi!</p>                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto veniam accusantium incidunt? Rerum quasi earum modi? Id, quo saepe. Sed minima facere enim, sunt vel numquam ipsum dolorum magnam porro ab perspiciatis temporibus cupiditate et quasi aliquam rerum quidem inventore provident distinctio cum! Similique, atque? Ex labore ullam repudiandae, quaerat provident quia totam mollitia odio, ipsum at, rerum praesentium? Eos, ea corporis. Tempore consequatur rem fugiat mollitia odio sed perferendis itaque ea. Deserunt error libero optio quo! Adipisci, placeat magni!</p>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit, velit accusamus repudiandae eum praesentium asperiores beatae, quaerat exercitationem facere, cum molestias nam? Nobis nemo doloremque dolores ea repudiandae fugit provident.</p>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laudantium exercitationem minus animi voluptate. Voluptates ad ipsa, magni dolorem quibusdam unde saepe sint ratione, corrupti dolor id nulla, quae quidem similique assumenda iste voluptas tempora nam velit. Neque repudiandae voluptatem cum tenetur amet impedit ratione eos similique laudantium perferendis! Facilis, voluptates est pariatur, debitis veniam iste odio neque quod assumenda nulla nihil. Libero fuga id nulla distinctio incidunt similique ipsam consectetur. Facilis voluptates aliquid consectetur quibusdam sit deleniti nesciunt maiores corporis esse aperiam praesentium, omnis totam hic eligendi voluptatum assumenda voluptatibus!</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor temporibus esse cupiditate ipsum praesentium voluptatibus, unde sequi beatae ullam modi soluta odio quo possimus molestiae facilis expedita illo explicabo quidem quasi quaerat dolorem reiciendis. Quas et consequuntur impedit ipsum repudiandae voluptates modi, architecto omnis. Ducimus delectus ex nesciunt optio alias laudantium excepturi, tempora rem nulla cumque obcaecati aut asperiores ratione earum ullam nihil dolor quisquam fugiat quia magnam quidem laboriosam? Corrupti autem libero ea voluptatum mollitia, quaerat numquam facilis illum quis rerum cupiditate? Atque vitae, assumenda neque labore eligendi eaque sapiente. Odio iure id voluptatem sint voluptatum! Eaque, vero deserunt! Soluta, atque cupiditate fuga nam in sed facilis natus nihil doloremque consectetur impedit deserunt molestiae error, debitis dolor laboriosam? Sed?</p>

                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laudantium modi quibusdam ipsum veritatis molestias tempore itaque possimus totam minus inventore quis saepe voluptatum quae aliquam, ipsa, nihil in consectetur distinctio maiores! Repellat odio pariatur, eveniet blanditiis provident ullam inventore illo dolore, nesciunt rem minima error! Et at tenetur possimus dignissimos recusandae temporibus tempore eius mollitia incidunt repellendus exercitationem hic minus ratione atque perspiciatis earum molestiae, laudantium voluptate optio nulla deserunt iusto. Hic aspernatur nam, vero dolorem dolores velit et commodi, minima necessitatibus vitae, cum beatae assumenda ea amet fugit officia est. Dolores minima aliquid praesentium accusamus eum laudantium tenetur voluptatibus at magni. Ea tempora obcaecati incidunt, ratione eveniet quia veniam a commodi maxime suscipit illo libero explicabo sint iusto officiis. Dolores, minus deserunt eos nostrum nisi consectetur. Impedit doloribus excepturi minus, facere adipisci velit laboriosam nobis sequi saepe incidunt. In, reiciendis! Reprehenderit perferendis maxime placeat repudiandae sit assumenda iure minima tempore sint illo iusto, blanditiis iste? Nobis, rem iusto. Dignissimos quidem perferendis expedita at, excepturi obcaecati non iusto soluta, tempora, et ipsam nihil? Minima officia amet esse, animi error maiores voluptate omnis autem repellendus blanditiis consectetur quas fugiat ex possimus soluta? Recusandae nisi reiciendis odit sed laboriosam quia hic animi!

                </p>
            </div>
        </div>
    );
};

export default ScrollAnimations;